# fly.toml app configuration file generated for backend-red-resonance-2063 on 2024-09-01T22:48:00+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cloudmix'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  path = '/health'
  method = 'GET'
  interval = "30s"
  timeout = "5s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
